# Generated by Django 2.1.7 on 2019-04-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenster', '0004_apt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apt',
            name='fenster',
        ),
        migrations.AddField(
            model_name='fenster',
            name='altitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fenster',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fenster',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fenster',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Apt',
        ),
    ]
