# Generated by Django 2.1.7 on 2019-04-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenster', '0005_auto_20190422_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='fenster',
            name='status_of_object',
            field=models.BooleanField(default=1),
        ),
    ]
